const CONFIG = {
  VITEPRESS_COLOR_PRIMARY: '#3451b2',
  VITEPRESS_COLOR_BACKGROUND: '#f4f4f1',
  VITEPRESS_COLOR_SURFACE: '#ffffff',
  VITEPRESS_COLOR_TEXT: '#202321',
  VITEPRESS_COLOR_MUTED: '#68706b',

  VITEPRESS_MENU_SEARCH: true,

  VITEPRESS_SITE_NAME:
    process.env.NEXT_PUBLIC_VITEPRESS_SITE_NAME || 'yibo',
  VITEPRESS_AUTHOR: process.env.NEXT_PUBLIC_VITEPRESS_AUTHOR || 'yibo',
  VITEPRESS_FAVICON:
    process.env.NEXT_PUBLIC_VITEPRESS_FAVICON || '/yibo-favicon.svg',
  VITEPRESS_GITHUB:
    process.env.NEXT_PUBLIC_VITEPRESS_GITHUB ||
    'https://github.com/yibo9605-stack',
  VITEPRESS_ESSAY_PATH:
    process.env.NEXT_PUBLIC_VITEPRESS_ESSAY_PATH ||
    '/casualEssay/RollingStoneLoveStory',
  VITEPRESS_ESSAY_CATEGORY:
    process.env.NEXT_PUBLIC_VITEPRESS_ESSAY_CATEGORY || '心情随笔',
  VITEPRESS_ESSAY_TITLE: '随笔',
  VITEPRESS_ESSAY_DESCRIPTION: '记录生活、心情与沿途的思考。',

  VITEPRESS_HERO_BRAND:
    process.env.NEXT_PUBLIC_VITEPRESS_HERO_BRAND || 'yibo',
  VITEPRESS_HERO_TITLE:
    process.env.NEXT_PUBLIC_VITEPRESS_HERO_TITLE || '向内生长，向外探索',
  VITEPRESS_HERO_DESCRIPTION:
    process.env.NEXT_PUBLIC_VITEPRESS_HERO_DESCRIPTION ||
    '记录技术、生活与那些值得被记住的瞬间',

  VITEPRESS_HOME_EYEBROW: 'JOURNAL',
  VITEPRESS_HOME_TITLE: 'Blog',
  VITEPRESS_BLOG_DESCRIPTION:
    process.env.NEXT_PUBLIC_VITEPRESS_BLOG_DESCRIPTION ||
    '关于技术、生活与持续思考的文章。',
  VITEPRESS_SHOW_AUTHOR: true,
  VITEPRESS_SHOW_GITHUB: true
}

export default CONFIG
