const CONFIG = {
  VITEPRESS_COLOR_PRIMARY: '#3451b2',
  VITEPRESS_COLOR_BACKGROUND: '#f4f4f1',
  VITEPRESS_COLOR_SURFACE: '#ffffff',
  VITEPRESS_COLOR_TEXT: '#202321',
  VITEPRESS_COLOR_MUTED: '#68706b',

  VITEPRESS_MENU_CATEGORY: true,
  VITEPRESS_MENU_TAG: true,
  VITEPRESS_MENU_ARCHIVE: true,
  VITEPRESS_MENU_SEARCH: true,

  VITEPRESS_HOME_EYEBROW: 'JOURNAL',
  VITEPRESS_HOME_TITLE: 'Blog',
  VITEPRESS_SHOW_AUTHOR: true,
  VITEPRESS_SHOW_GITHUB: true
}

export default CONFIG
